---
title: "STAT4255 HW1"
author: "Roger Blake"
---

# Question 2:

Explain whether each scenario is a classification or regression problem, and indicate whether we are most interested in inference or prediction. Finally, provide n and p.

(a) We collect a set of data on the top 500 firms in the US. For each firm we record profit, number of employees, industry and the
CEO salary. We are interested in understanding which factors affect CEO salary.

    This is a regression problem because the target variable (salary) is continuous. The goal is inference because we are interested in understanding the factors that affect the salary, not predicting it. n=500 and p=3

(b) We are considering launching a new product and wish to know
whether it will be a success or a failure. We collect data on 20
similar products that were previously launched. For each product we have recorded whether it was a success or failure, price
charged for the product, marketing budget, competition price,
and ten other variables

    This is a classification problem (success/failure response variable) and the goal is prediction (predicting whether new, unseen data point will be success/failure). n=20 and p=13

(c) We are interested in predicting the % change in the USD/Euro
exchange rate in relation to the weekly changes in the world
stock markets. Hence we collect weekly data for all of 2012. For
each week we record the % change in the USD/Euro, the %
change in the US market, the % change in the British market,
and the % change in the German market.

    This is a regression problem (continuous response variable) and the goal is prediction (predicting % change in USD/Euro exchange rate). n=52 and p=3

# Question 4:

(a) Describe three real-life applications in which classification might be useful. Describe the response, as well as the predictors. Is the goal of each application inference or prediction? Explain your answer.

    - classification of medical data for cancer diagnosis (yes/no). Predictors would be scans and vitals information, and the goal would be inference so doctors could identify factors that might make someone more likely to get cancer.
    - classification of emails: spam/not spam. The predictors would be vocabulary used in the email, and the goal would be prediction.
    - classification of a student dropping out/not dropping out of college. The predictors would be family income level, gpa, major, etc. The goal would be inference so schools know which student they might need to give more resources to.

(b) Describe three real-life applications in which regression might be useful. Describe the response, as well as the predictors. Is the goal of each application inference or prediction? Explain your answer.

    - Analyzing salary level for a certain position. The response would be salary, and the predictors would be years of experience, age, education level, university rank, etc. The goal would be inference because we are interested in understanding what drives salary, not predicting it.
    - Analyzing real estate prices. The response would be house price, and the predictors would be square feet, number of bedrooms/bathrooms, location, etc. The goal would be prediction so sellers could know how much to list a house for. 
    - Analyzing mpg for a car. The response would be miles per gallon, and the predictors would be engine type, gas/diesel, vehicle weight, etc. The goal would be inference to see what factors influence mpg. 

(c) Describe three real-life applications in which cluster analysis might be useful.

    - grouping voters together for politicians. If groups of voters with similar values can be grouped together, a politician could emphasis certain parts of his/her message to tailor to the group's values.
    - clustering similar companies together to perform relative valuation. This would be useful for stock analysts because finding similar companies with different valuations shows opportunity.
    - grouping customers together with similar tastes for targeted advertising. 

# Question 7

(a) Compute the Euclidean distance between each observation and
the test point, X1 = X2 = X3 =0.
```{python}
import math
```

    - obs 1: sqrt(9) = 3
    - obs 2: sqrt(4) = 2
    - obs 3: sqrt(10) = `{python} math.sqrt(10)`
    - obs 4: sqrt(5) = `{python} math.sqrt(5)`
    - obs 5: sqrt(2) = `{python} math.sqrt(2)`
    - obs 6: sqrt(3) = `{python} math.sqrt(3)`

(b) What is our prediction with K =1? Why?

    - With K=1, observation 5 (-1, 0, 1) is our nearest neighbor, as shown above. It has the smallest distance. So green would be the prediction.

(c) What is our prediction with K =3? Why?

    - The three nearest neighbors are Green, Red, and Red. Since 2/3 (majority) are red, the prediction would be red.

(d) If the Bayes decision boundary in this problem is highly nonlinear, then would we expect the best value for K to be large or small? Why?

    - We would expect the best value for K to be small. This keeps the bias low and the flexibility/variance high, allowing for a highly nonlinear shape.

# Question 8:

(a)
```{python}
import pandas as pd
import matplotlib.pyplot as plt

college = pd.read_csv("College.csv")
```

(b)
```{python}
college
```

```{python}
college2 = pd.read_csv('College.csv', index_col=0)
college3 = college.rename({'Unnamed: 0': 'College'},
axis=1)
college3 = college3.set_index('College')
```

```{python}
college = college3
college
```

(c)

```{python}
college.describe()
```

(d)

```{python}
pd.plotting.scatter_matrix(college[["Top10perc", "Apps", "Enroll"]])
```

(e)

```{python}
college.boxplot(column="Outstate", by="Private")
```

(f)

```{python}
# copied from the textbook
college['Elite'] = pd.cut(college['Top10perc'],
                            [0,0.5,1],
                            labels=['No', 'Yes'])

college["Elite"].value_counts()
```

```{python}
college.boxplot(column="Outstate", by="Elite")
```

(g)

```{python}
fig, axes = plt.subplots(2,2)
college['Enroll'].plot.hist(ax=axes[0, 0], bins=10, title='Apps (10 bins)', edgecolor='black')
college['Outstate'].plot.hist(ax=axes[0, 1], bins=30, title='Apps (30 bins)', edgecolor='black')
college['Outstate'].plot.hist(ax=axes[1, 0], bins=15, title='Outstate Tuition', edgecolor='black')
college['Grad.Rate'].plot.hist(ax=axes[1, 1], bins=15, title='Graduation Rate', edgecolor='black')
plt.show()
```

(h)

Let's look further at what factors correlate with graduation rate:
```{python}
college.corr(numeric_only=True)['Grad.Rate']
```

Outstate, top10perc, top25perc, and perc.alumni have the largest positive correlation. Outstate sticks out to me as a little bit of a surprise, but I suppose students who travel out of state for college are probably wealthier and more committed to the school.

S.F.Ratio and P.Undergrad have the largest negative impact. This makes sense, as schools with smaller student/faculty ratios graduate more students. Schools with higher levels of part time students are probably mostly state schools/community colleges, which most likely have a lower graduation rate.

# Question 10:

(a)
```{python}
import pandas as pd
import matplotlib.pyplot as plt
from ISLP import load_data

Boston = load_data("Boston")
```

(b)
```{python}
Boston.head()
Boston.shape
```

The rows are towns and the columns are variables about each town.

(c)

```{python}
pd.plotting.scatter_matrix(Boston, figsize=(12,12))
plt.show()
```

(d)

```{python}
Boston.corr(numeric_only=True)['crim']
```

(e)

```{python}
for col in ["crim", "tax", "ptratio"]:
    print(col, Boston[col].max(), Boston[col].max()-Boston[col].min())
```

(f)

```{python}
(Boston["chas"]==1).sum()
```

(g)

```{python}
Boston["ptratio"].median()
```

(h)

```{python}
Boston.loc[Boston["medv"].idxmin()]
```

```{python}
Boston.describe()
```

(i)

```{python}
(Boston["rm"] > 7).sum()
```

```{python}
(Boston["rm"] > 8).sum()
```

```{python}
Boston[Boston['rm'] > 8].describe()
```
